name: uncertwin
channels:
   - conda-forge
dependencies:
    - python==3.7.3
    - blas=*=openblas
    - sympy==1.3               # Sympy 1.4 does not work with Pyinstaller 3.4.
    - numpy==1.16.4
    - matplotlib-base==3.1.1   # Install -base to avoid duplicating pyqt
    - setuptools==44.0
    - pyyaml==5.1
    - markdown==3.1
    - pint==0.9
    - pip==19.1.1
    - pip:
        - pyqt5==5.12.2     # Conda-installed pyqt is broken in pyinstaller 3.4. Install it with pip.
        - PyInstaller==3.5
        - scipy==1.1.0        # Install from pip because openblas version N/A in conda or conda-forge.
