name: uncertosx
dependencies:
    - nomkl>=1.0      # Prevent requiring the Intel MKL dll which don't play nice with pyinstaller
    - python==3.7
    - sympy==1.3
    - scipy==1.1.0
    - numpy==1.15.1
    - matplotlib==2.2.3
    - setuptools>=40.2
    - pyyaml==3.13
    - markdown==2.6.11
#   - pandoc                # Optional for building documentation and saving Docx, ODT, or PDF outputs
    - pip:
        - pyqt5==5.11.2     # Conda-installed pyqt is broken in pyinstaller 3.4. Install it with pip.
        - PyInstaller==3.4
#       - pandoc-fignos     # Used for building user manual via pandoc
