name: uncertwin
channels:
   - conda-forge
dependencies:
    - python==3.7
    - blas=*=openblas
    - sympy==1.3
    - numpy==1.15.2
    - matplotlib-base==3.0.3   # Install -base to avoid duplicating pyqt
    - setuptools>=40
    - pyyaml==3.13
    - markdown==3.0.1
    - pip:
        - pyqt5==5.11.2     # Conda-installed pyqt is broken in pyinstaller 3.4. Install it with pip.
        - PyInstaller==3.4
        - scipy==1.1.0      # Install from pip because openblas version N/A in conda or conda-forge